-- Generated from assets/food/nutrient_defs.json. Re-run after editing that file.

insert into nutrient_defs (code, name_nl, unit, "group", decimals, is_core, sort_order) values
  ('ENERCC', 'Energie', 'kcal', 'energy', 0, true, 10),
  ('ENERC', 'Energie', 'kJ', 'energy', 0, false, 11),
  ('PROT', 'Eiwit', 'g', 'macro', 1, true, 20),
  ('PROTPL', 'Plantaardig eiwit', 'g', 'macro', 1, false, 21),
  ('PROTAN', 'Dierlijk eiwit', 'g', 'macro', 1, false, 22),
  ('FAT', 'Vet', 'g', 'macro', 1, true, 30),
  ('CHO', 'Koolhydraten', 'g', 'macro', 1, true, 40),
  ('FIBT', 'Vezels', 'g', 'macro', 1, true, 50),
  ('ALC', 'Alcohol', 'g', 'macro', 1, true, 60),
  ('WATER', 'Water', 'g', 'macro', 1, false, 70),
  ('ASH', 'As', 'g', 'other', 1, false, 80),
  ('SUGAR', 'Suikers', 'g', 'carb', 1, true, 100),
  ('STARCH', 'Zetmeel', 'g', 'carb', 1, false, 101),
  ('FRUS', 'Fructose', 'g', 'carb', 1, false, 102),
  ('GLUS', 'Glucose', 'g', 'carb', 1, false, 103),
  ('SUCS', 'Sucrose', 'g', 'carb', 1, false, 104),
  ('LACS', 'Lactose', 'g', 'carb', 1, false, 105),
  ('FASAT', 'Verzadigd vet', 'g', 'fat', 1, true, 200),
  ('FAMSCIS', 'Enkelvoudig onverzadigd vet (cis)', 'g', 'fat', 1, false, 201),
  ('FAPU', 'Meervoudig onverzadigd vet', 'g', 'fat', 1, false, 202),
  ('FATRN', 'Transvet', 'g', 'fat', 2, false, 203),
  ('FAPUN3', 'n-3 vetzuren', 'g', 'fat', 2, false, 204),
  ('FAPUN6', 'n-6 vetzuren', 'g', 'fat', 2, false, 205),
  ('CHOLE', 'Cholesterol', 'mg', 'fat', 0, false, 206),
  ('FA18:2CN6', 'Linolzuur', 'g', 'fat', 2, false, 210),
  ('FA18:3CN3', 'Alfa-linoleenzuur', 'g', 'fat', 2, false, 211),
  ('FA20:5CN3', 'EPA', 'g', 'fat', 2, false, 212),
  ('FA22:6CN3', 'DHA', 'g', 'fat', 2, false, 213),
  ('NA', 'Natrium', 'mg', 'mineral', 0, true, 300),
  ('K', 'Kalium', 'mg', 'mineral', 0, false, 301),
  ('CA', 'Calcium', 'mg', 'mineral', 0, false, 302),
  ('P', 'Fosfor', 'mg', 'mineral', 0, false, 303),
  ('MG', 'Magnesium', 'mg', 'mineral', 0, false, 304),
  ('FE', 'IJzer', 'mg', 'mineral', 1, false, 305),
  ('HAEM', 'Heemijzer', 'mg', 'mineral', 1, false, 306),
  ('NHAEM', 'Non-heemijzer', 'mg', 'mineral', 1, false, 307),
  ('CU', 'Koper', 'mg', 'mineral', 2, false, 308),
  ('ZN', 'Zink', 'mg', 'mineral', 1, false, 309),
  ('SE', 'Seleen', 'µg', 'mineral', 0, false, 310),
  ('ID', 'Jodium', 'µg', 'mineral', 0, false, 311),
  ('MN', 'Mangaan', 'mg', 'mineral', 2, false, 312),
  ('VITA', 'Vitamine A', 'µg', 'vitamin', 0, false, 400),
  ('RETOL', 'Retinol', 'µg', 'vitamin', 0, false, 401),
  ('CARTBEQ', 'Bètacaroteen-equivalent', 'µg', 'vitamin', 0, false, 402),
  ('CARTB', 'Bètacaroteen', 'µg', 'vitamin', 0, false, 403),
  ('VITD', 'Vitamine D', 'µg', 'vitamin', 1, false, 404),
  ('VITE', 'Vitamine E', 'mg', 'vitamin', 1, false, 405),
  ('VITK', 'Vitamine K', 'µg', 'vitamin', 0, false, 406),
  ('THIA', 'Vitamine B1', 'mg', 'vitamin', 2, false, 407),
  ('RIBF', 'Vitamine B2', 'mg', 'vitamin', 2, false, 408),
  ('NIA', 'Niacine', 'mg', 'vitamin', 1, false, 409),
  ('NIAEQ', 'Niacine-equivalent', 'mg', 'vitamin', 1, false, 410),
  ('VITB6', 'Vitamine B6', 'mg', 'vitamin', 2, false, 411),
  ('FOL', 'Foliumzuur', 'µg', 'vitamin', 0, false, 412),
  ('FOLFD', 'Foliumzuur uit voedsel', 'µg', 'vitamin', 0, false, 413),
  ('FOLAC', 'Foliumzuur toegevoegd', 'µg', 'vitamin', 0, false, 414),
  ('VITB12', 'Vitamine B12', 'µg', 'vitamin', 2, false, 415),
  ('VITC', 'Vitamine C', 'mg', 'vitamin', 0, false, 416)
on conflict (code) do update set
  name_nl = excluded.name_nl,
  unit = excluded.unit,
  "group" = excluded."group",
  decimals = excluded.decimals,
  is_core = excluded.is_core,
  sort_order = excluded.sort_order;
